# Generated by Django 5.2 on 2025-05-24 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='es_valido',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documento',
            name='observacion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
