# Generated by Django 5.2 on 2025-06-06 16:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_documento_creado_por'),
    ]

    operations = [
        migrations.CreateModel(
            name='Importado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_importador', models.CharField(max_length=50)),
                ('nombre_importador', models.CharField(max_length=100)),
                ('actividad_economica', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_persona', models.CharField(blank=True, max_length=50, null=True)),
                ('direccion_importador', models.CharField(blank=True, max_length=200, null=True)),
                ('telefono_importador', models.CharField(blank=True, max_length=20, null=True)),
                ('correo_importador', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_registro', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Embarque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_contenedor', models.CharField(max_length=50)),
                ('descripcion_carga', models.TextField(blank=True, null=True)),
                ('fecha_salida', models.DateField()),
                ('ubicacion_salida', models.CharField(blank=True, max_length=100, null=True)),
                ('ubicacion_llegada', models.CharField(blank=True, max_length=100, null=True)),
                ('monto_embarque', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('buque_embarque', models.CharField(blank=True, max_length=100, null=True)),
                ('peso_embarque', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('importador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.importado')),
            ],
        ),
        migrations.CreateModel(
            name='Seguimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_seguimiento', models.DateField()),
                ('ubicacion_seguimiento', models.CharField(blank=True, max_length=100, null=True)),
                ('status_seguimiento', models.CharField(blank=True, max_length=50, null=True)),
                ('embarque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.embarque')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
