# Generated by Django 5.2 on 2025-06-06 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_importado_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='embarque',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion.embarque'),
        ),
        migrations.AlterField(
            model_name='importado',
            name='fecha_registro',
            field=models.DateField(auto_now_add=True),
        ),
    ]
