# Generated by Django 5.2 on 2025-06-06 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_documento_embarque_alter_importado_fecha_registro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='tipo',
            field=models.CharField(choices=[('Factura', 'Factura'), ('Guía', 'Guía de Transporte'), ('Packing', 'Packing List'), ('Certificado', 'Certificado de Origen'), ('Otro', 'Otro')], max_length=100),
        ),
    ]
